// Autogenerated by SignalrTypescriptGenerator.exe at 03/09/2016 11:44:02

// Get signalr.d.ts.ts from https://github.com/borisyankov/DefinitelyTyped (or delete the reference)
/// <reference path="signalr/signalr.d.ts" />
/// <reference path="jquery/jquery.d.ts" />

// Hubs
interface SignalR
{
	taskMonitorHub : Syringe.Service.Controllers.Hubs.TaskMonitorHub;
}

// Service contracts

declare module Syringe.Service.Controllers.Hubs
{

	interface TaskMonitorHub
	{
		server : Syringe.Service.Controllers.Hubs.TaskMonitorHubServer;
		client : Syringe.Service.Controllers.Hubs.ITaskMonitorHubClient;
	}

	interface TaskMonitorHubServer
	{
		startMonitoringTask(taskId : number) : JQueryPromise<Syringe.Service.Controllers.Hubs.TaskState>;
	}
}


// Clients

declare module Syringe.Service.Controllers.Hubs
{
	interface ITaskMonitorHubClient
	{
		onTaskCompleted : (taskInfo : Syringe.Service.Controllers.Hubs.CompletedTaskInfo) => void;
		onTestFileGuid : (guid : string) => void;
	}
}


// Data contracts

declare module Syringe.Service.Controllers.Hubs
{
	interface CompletedTaskInfo
	{
		Success : boolean;
		Position : number;
	}
}


declare module Syringe.Service.Controllers.Hubs
{
	interface TaskState
	{
		TotalTests : number;
	}
}


// Enums
